transcript_extraction:
  description: >
    Extract the complete transcript and metadata for the YouTube video: {video_url}.
    
    Steps to complete:
    1. Extract video ID from the provided URL
    2. Fetch video metadata (title, upload date, description, channel info)
    3. Retrieve the English transcript using available methods
    4. Process transcript into semantically coherent chunks preserving timestamps
    5. Structure all data into the standardized JSON format
    
    Handle errors gracefully and provide detailed status information.
  expected_output: >
    A structured JSON object containing:
    - Video metadata (title, URL, upload date, channel, description, thumbnail)
    - Processed transcript chunks with timestamps and unique IDs
    - Processing status and any encountered issues
  agent: transcript_researcher
  context: []

lecture_summarization:
  description: >
    Generate concise, high-value lecture notes from YouTube transcripts focusing on essential information.
    
    **Key Requirements:**
    1. Create an executive summary (1 paragraph, 3-4 sentences max)
    2. Extract only the most important concepts using the 80/20 rule
    3. Organize content into MAX 5 key sections with clear headings
    4. Include ONLY critical technical details (remove redundant examples)
    5. Add "Key Takeaways" section with 3-5 bullet points of actionable insights
    
    **Formatting Rules:**
    - Use strict Markdown formatting
    - Apply heading hierarchy: ## for sections, ### for subsections
    - Use bullet points for lists
    - Bold key terms and concepts
    - Keep total output under 400 words for a 25-minute video
    
    **Content Selection Guidelines:**
    - Prioritize novel information over basic concepts
    - Preserve unique insights and methodologies
    - Omit introductory fluff and repetitive explanations
    - Focus on practical applications over theoretical deep dives
  expected_output: >
    Concise lecture notes in Markdown format with:
    - 1-paragraph Executive Summary
    - 3-5 Key Sections with minimal subpoints
    - Bolded Key Terms
    - 3-5 Key Takeaways
    - Total word count: 300-400 words
  agent: lecture_summarizer
  context: [transcript_extraction]


tool_extraction:
  description: >
    Perform comprehensive named entity recognition to identify all AI tools, 
    frameworks, libraries, and platforms mentioned in the transcript.
    
    Extraction criteria:
    1. AI/ML frameworks (TensorFlow, PyTorch, etc.)
    2. Libraries and packages (scikit-learn, pandas, etc.)
    3. Cloud platforms and services (AWS, GCP, Azure ML, etc.)
    4. Development tools and IDEs
    5. Databases and vector stores
    6. Deployment and MLOps tools
    
    For each identified tool, capture:
    - Exact name and variations
    - Context of mention
    - Timestamp location
    - Tool category/type
    - Brief description of usage context
  expected_output: >
    Structured JSON array where each object contains:
    - tool_name: Official name of the tool
    - category: Tool classification (framework, library, platform, etc.)
    - context_snippet: Surrounding text where mentioned
    - timestamp: Location in video
    - confidence_score: Extraction confidence (0.0-1.0)
    - usage_context: Brief description of how tool was discussed
  agent: ai_tool_analyst
  context: [transcript_extraction]
